# Generated by Django 3.2 on 2021-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=2000)),
                ('solucionado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
